version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=8080
      - DB=postgres://postgres:postgres@db:5432/blogaggregator?sslmode=disable

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blogaggregator
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  psql:
    image: postgres:14-alpine
    environment:
      - PGPASSWORD=postgres
    depends_on:
      - db
    command: psql -h db -U postgres -d blogaggregator

volumes:
  postgres_data: